export COMPOSE_PROJECT_NAME=example-project2

export SEAMLESS_HASHSERVER_DIRECTORY=$(pwd)/buffers
export HASHSERVER_LAYOUT=prefix
export SEAMLESS_DATABASE_DIRECTORY=$(pwd)/database2
export SEAMLESS_HASHSERVER_PORT=5579
export SEAMLESS_DATABASE_PORT=5524
export SEAMLESS_ASSISTANT_PORT=5535