export COMPOSE_PROJECT_NAME=example-project

export SEAMLESS_HASHSERVER_DIRECTORY=$(pwd)/buffers
export HASHSERVER_LAYOUT=prefix
export SEAMLESS_DATABASE_DIRECTORY=$(pwd)/database
export SEAMLESS_HASHSERVER_PORT=5578
export SEAMLESS_DATABASE_PORT=5523
export SEAMLESS_ASSISTANT_PORT=5534