channels:
  - rpbs
  - conda-forge
dependencies:
  - cloudpickle=3
  - gcc
  - gxx
  - gfortran
  - pip
  - pip:
      - distributed==2024.9.0
      - dask[distributed]
      - dask-jobqueue
      - lz4
      - jsonschema==4.18
      - requests==2.31
variables:
  SEAMLESS_READ_BUFFER_SERVERS:
  SEAMLESS_WRITE_BUFFER_SERVER:
